# Generated by Django 5.2.7 on 2025-10-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_compare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.TextField()),
                ('right_text', models.TextField()),
                ('left_diff_html', models.TextField(blank=True)),
                ('right_diff_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comparison',
        ),
    ]
